<a href="https://colab.research.google.com/github/Himagination/PyTorch/blob/main/First_Hands_On_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tensor as Numpy n-dimensional array.

In [1]:
import numpy as np

v0 = np.array(1.3)
v1 = np.array([1., 2., 3,])
v2 = np.array([[1., 2., 3.], 
               4., 5., 6.])
print(f"{v0}, {v1}, {v2}")

1.3, [1. 2. 3.], [list([1.0, 2.0, 3.0]) 4.0 5.0 6.0]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


## Create a Tensor from Numpy

In [2]:
numpy_array = np.array([1, 2, 3])

### Notes on torch.Tensor
-  torch.Tensor is a main class of Tensor. All other tensors are instance of Tensor class and inherit from this main class.
-  Constructor - is same as torch.FloatTensor hence by default it produces tensor of type float32. This can be a disadvantage as float32 takes more size of bit.

In [3]:
import torch
t1 = torch.Tensor(numpy_array)
t1

tensor([1., 2., 3.])

### Notes on torch.tensor
-  It is a Factory function.
-  It produces tensor of same data type as input.
-  It does not share underlying memory with numpy i.e t2 and numpy_array in above case will have two different memory allocation.
-  It always copies the data i.e modifying the value of t2 won't affect the value of numpy_array.
-  Syntax: torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False)
- Recommended to use.

In [4]:
t2 = torch.tensor(numpy_array)
t2

tensor([1, 2, 3])

### Notes on torch.as_tensor()
-  Factory Function
-  Produces tensor of same data type.
-  Shares the underlying memory with numpy.
-  Can accept any array like Python Data Structure i.e not limited to Numpy.
-  Syntax: torch.as_tensor(data, dtype=None, device=None)
-  We have to manually call requires_grad() function on the final tensor. Does not support as argument by default.
-  Recommended to use.
-  numpy.array objects are allocated on CPU, as_tensor() function must copy the data from CPU to GPU when a GPU is being used.
-  The memory sharing of as_tensor() doesn't work with built-in Python Data Structure like list.
-  The as_tensor() performance improvement will be greater when there are a lot of back and forthoperations between numpy.array objects and tensor objects. 

In [5]:
t3 = torch.as_tensor(numpy_array)
t3

tensor([1, 2, 3])

### Notes on torch.from_numpy()
-  Factory function
-  Produces a new tensor with the same data type
-  Share the underlying memory with numpy.
-  CAN ACCEPT ONLY NUMPY ARRAYS.
-  Syntax: torch.from_numpy(ndarray)

In [6]:
t4 = torch.from_numpy(numpy_array)
t4

tensor([1, 2, 3])

### Changing values

In [7]:
numpy_array *= 4
numpy_array

array([ 4,  8, 12])

In [8]:
t1, t2, t3, t4

(tensor([1., 2., 3.]),
 tensor([1, 2, 3]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [9]:
t1 *= 2
numpy_array, t1, t2, t3, t4

(array([ 4,  8, 12]),
 tensor([2., 4., 6.]),
 tensor([1, 2, 3]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [10]:
t2 *= 2
numpy_array, t1, t2, t3, t4

(array([ 4,  8, 12]),
 tensor([2., 4., 6.]),
 tensor([2, 4, 6]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [11]:
t3 *= 2
numpy_array, t1, t2, t3, t4

(array([ 8, 16, 24]),
 tensor([2., 4., 6.]),
 tensor([2, 4, 6]),
 tensor([ 8, 16, 24]),
 tensor([ 8, 16, 24]))

In [12]:
t4 *= 2
numpy_array, t1, t2, t3, t4

(array([16, 32, 48]),
 tensor([2., 4., 6.]),
 tensor([2, 4, 6]),
 tensor([16, 32, 48]),
 tensor([16, 32, 48]))

In [13]:
t5 = t4.cuda()
t5.device, t4.device

(device(type='cuda', index=0), device(type='cpu'))

In [14]:
t6 = t5 + t4
t6

RuntimeError: ignored

# Autograd
- Automatic differentiation for all operations on Tensors
- The backward graph is automatically defined by the forward graph.

In [15]:
x1 = torch.tensor(2, requires_grad=True, dtype=torch.float16)
x2 = torch.tensor(3, requires_grad=True, dtype=torch.float16)
x3 = torch.tensor(4, requires_grad=True, dtype=torch.float16)
x4 = torch.tensor(5, requires_grad=True, dtype=torch.float16)

x1, x2, x3, x4

(tensor(2., dtype=torch.float16, requires_grad=True),
 tensor(3., dtype=torch.float16, requires_grad=True),
 tensor(4., dtype=torch.float16, requires_grad=True),
 tensor(5., dtype=torch.float16, requires_grad=True))

In [17]:
from torch.autograd import grad

z1 = x1 * x2
z2 = x3 * x4
f = z1 + z2
# f = x1 * x2 + x3 * x4

df_dx = grad(outputs=f, inputs=[x1, x2, x3, x4])
print(f'gradient of x1 = {df_dx[0]}')
print(f'gradient of x2 = {df_dx[1]}')
print(f'gradient of x3 = {df_dx[2]}')
print(f'gradient of x4 = {df_dx[3]}')

gradient of x1 = 3.0
gradient of x2 = 2.0
gradient of x3 = 5.0
gradient of x4 = 4.0


In [20]:
y1 = torch.tensor(2, requires_grad=True, dtype=torch.float16)
y2 = torch.tensor(3, requires_grad=True, dtype=torch.float16)
y3 = torch.tensor(4, requires_grad=True, dtype=torch.float16)
y4 = torch.tensor(5, requires_grad=True, dtype=torch.float16)

z1 = y1 * y2
z2 = y3 * y4
f = z1 + z2
f.backward()
print(f'gradient of x1 = {y1.grad}')
print(f'gradient of x2 = {y2.grad}')
print(f'gradient of x3 = {y3.grad}')
print(f'gradient of x4 = {y4.grad}')

gradient of x1 = 3.0
gradient of x2 = 2.0
gradient of x3 = 5.0
gradient of x4 = 4.0


# Squeezing the Tensor
- Squeeze: Removes all the dimensions that have length of 1
- Unsqueeze: Adds a dimension that has a length of 1

**Why is it required?**

*Neural Networks are always trained in a batch of samples. This is troubling because when we want to test 1 image, we do not have an array, we only have 1 image. Then we unsqueeze to fake a batch.*


In [21]:
# Checking shape, size, number of elements for Tensor
t = torch.tensor([
                  [0, 0, 0, 0], 
                  [1, 2, 3, 4], 
                  [2, 2, 2, 2]
], dtype=torch.float32)
t.shape, t.size(), t.numel()

(torch.Size([3, 4]), torch.Size([3, 4]), 12)

In [22]:
print(t.reshape(1, 12))
print(t.reshape(1, 12).shape)

tensor([[0., 0., 0., 0., 1., 2., 3., 4., 2., 2., 2., 2.]])
torch.Size([1, 12])


In [23]:
print(t.reshape(1, 12).squeeze())
print(t.reshape(1, 12).squeeze().shape)

tensor([0., 0., 0., 0., 1., 2., 3., 4., 2., 2., 2., 2.])
torch.Size([12])


In [24]:
print(t.reshape(1, 12).squeeze().unsqueeze(0))
print(t.reshape(1, 12).squeeze().unsqueeze(0).shape)

tensor([[0., 0., 0., 0., 1., 2., 3., 4., 2., 2., 2., 2.]])
torch.Size([1, 12])


## Flattening the Tensor.
It creates a new Tensor that is only 1D. It is done to connect our data to next Fully Connected Layers

In [25]:
def flatten(t):
  t = t.reshape(1, -1)
  t = t.squeeze()
  return t

In [26]:
t.shape

torch.Size([3, 4])

In [27]:
flatten(t)

tensor([0., 0., 0., 0., 1., 2., 3., 4., 2., 2., 2., 2.])